development:
  adapter: mysql2
  database: <%= ENV["MYSQL_DATABASE"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV["DATABASE_SERVICE_HOST"] %>
  port: <%= ENV["DATABASE_SERVICE_PORT"] %>

test:
  adapter: mysql2
  database: <%= ENV["MYSQL_DATABASE"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV["DATABASE_TEST_SERVICE_HOST"] %>
  port: <%= ENV["DATABASE_TEST_SERVICE_PORT"] %>

production:
  adapter: mysql2
  database: <%= ENV["MYSQL_DATABASE"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV["DATABASE_SERVICE_HOST"] %>
  port: <%= ENV["DATABASE_SERVICE_PORT"] %>
